version: '3.7'
services:
  vue-service:
    container_name: 'vue3-test' 
    build: 
      context: .
      target: 'dev-stage'
    volumes:
      - '.:/usr/src/app'
    ports: 
      - '8080:8080'
    command: >
      bash -c "npm install && npm run serve"
